# -*- coding: utf-8 -*-
"""KPOP_ReEntry_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPOAXDqhIU3JVmOWPo2l4NxO0vVqBVd4
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

print("Libraries Loaded Successfully")
df.drop_duplicates(inplace=True)

print("New Shape:", df.shape)

df = pd.read_csv('/content/Atlantic_South_Korea.csv')

print("Dataset Loaded Successfully")

print(df.shape)

df.head()

df.info()

df.isnull().sum()

print(df.duplicated().sum())

print("Total Records :", len(df))
print("Total Columns :", len(df.columns))

print("\nColumns:")
print(df.columns.tolist())

print("Unique Songs :", df['song'].nunique())
print("Unique Artists :", df['artist'].nunique())

df['date'] = pd.to_datetime(df['date'])

print("Start Date :", df['date'].min())
print("End Date :", df['date'].max())

df['duration_min'] = df['duration_ms'] / 60000

df[['duration_ms','duration_min']].head()

df['song_id'] = df['song'].astype(str) + " - " + df['artist'].astype(str)

df[['song','artist','song_id']].head()

df.describe()

top_artists = df['artist'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_artists.plot(kind='bar')
plt.title("Top 10 Artists")
plt.xlabel("Artist")
plt.ylabel("Appearances")
plt.show()

df['album_type'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title("Album Type Distribution")
plt.show()

sns.countplot(x='is_explicit', data=df)

plt.title("Explicit vs Non Explicit Songs")
plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df['popularity'], bins=20)

plt.title("Popularity Distribution")
plt.show()

# Create Song ID

df['song_id'] = (
    df['song'].astype(str)
    + " - " +
    df['artist'].astype(str)
)

print("song_id created successfully")

print(df.columns.tolist())

# Remove duplicates

df.drop_duplicates(inplace=True)

# Sort dataset

df = df.sort_values(
    by=['song_id','date']
).reset_index(drop=True)

print("Dataset ready")
print(df.shape)

reentry_df = df[
    [
        'song_id',
        'song',
        'artist',
        'date',
        'position',
        'popularity',
        'album_type',
        'is_explicit'
    ]
].copy()

print("Reentry dataframe created")
reentry_df.head()

reentry_df['previous_date'] = (
    reentry_df.groupby('song_id')['date']
    .shift(1)
)

reentry_df.head()

print(reentry_df.dtypes)

reentry_df['date'] = pd.to_datetime(
    reentry_df['date'],
    errors='coerce'
)

print(reentry_df['date'].dtype)

reentry_df['previous_date'] = (
    reentry_df.groupby('song_id')['date']
    .shift(1)
)

print(reentry_df['previous_date'].dtype)

reentry_df['gap_days'] = (
    reentry_df['date']
    -
    reentry_df['previous_date']
).dt.days

reentry_df[
    ['song','date','previous_date','gap_days']
].head(20)

print(reentry_df.dtypes)

reentry_df['is_reentry'] = (
    reentry_df['gap_days'] > 1
)

reentry_df[
    ['song','date','gap_days','is_reentry']
].head(20)

reentries = reentry_df[
    reentry_df['is_reentry'] == True
]

print("Total Re-Entries Found:", len(reentries))

reentries[
    [
        'song',
        'artist',
        'date',
        'gap_days',
        'position'
    ]
].head(20)

reentry_counts = (
    reentries.groupby('song_id')
    .size()
    .reset_index(name='reentry_count')
)

reentry_counts = reentry_counts.sort_values(
    by='reentry_count',
    ascending=False
)

reentry_counts.head(10)

print(df['date'].nunique())
print(df['date'].sort_values().unique()[:20])

df['date'] = pd.to_datetime(
    df['date'],
    format='%d-%m-%Y'
)

print(df['date'].dtype)

print(df['date'].min())
print(df['date'].max())

reentry_df = df[
    [
        'song_id',
        'song',
        'artist',
        'date',
        'position',
        'popularity',
        'album_type',
        'is_explicit'
    ]
].copy()

dates = sorted(df['date'].unique())

print("First 20 Dates:")
print(dates[:20])

print(dates[:20])

reentry_df = df.copy()

reentry_df = reentry_df.sort_values(
    ['song_id','date']
)

reentry_df['previous_date'] = (
    reentry_df.groupby('song_id')['date']
    .shift(1)
)

reentry_df['gap_days'] = (
    reentry_df['date']
    -
    reentry_df['previous_date']
).dt.days

reentry_df[['song','date','gap_days']].head(20)

reentry_df['is_reentry'] = (
    reentry_df['gap_days'] > 1
)

print(
    "Potential Re-Entries:",
    reentry_df['is_reentry'].sum()
)

reentries = reentry_df[
    reentry_df['is_reentry'] == True
]

reentries[
    [
        'song',
        'artist',
        'date',
        'gap_days',
        'position'
    ]
].head(20)

reentries['gap_days'].describe()

reentry_counts = (
    reentries.groupby(
        ['song','artist']
    )
    .size()
    .reset_index(
        name='reentry_count'
    )
)

reentry_counts = (
    reentry_counts.sort_values(
        by='reentry_count',
        ascending=False
    )
)

reentry_counts.head(20)

top10 = reentry_counts.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10,
    x='reentry_count',
    y='song'
)

plt.title(
    'Top 10 Songs by Re-Entry Frequency'
)

plt.show()

reentry_counts.to_csv(
    'reentry_frequency.csv',
    index=False
)

print(
    "KPI 1 Saved Successfully"
)

reentries['momentum_score'] = (
    51 - reentries['position']
)

reentries[
    [
        'song',
        'artist',
        'position',
        'momentum_score'
    ]
].head()

momentum_table = (
    reentries.groupby(
        ['song','artist']
    )['momentum_score']
    .mean()
    .reset_index()
)

momentum_table = (
    momentum_table.sort_values(
        by='momentum_score',
        ascending=False
    )
)

momentum_table.head(20)

top10_momentum = momentum_table.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10_momentum,
    x='momentum_score',
    y='song'
)

plt.title(
    'Top 10 Songs by Momentum Score'
)

plt.show()

momentum_table.to_csv(
    'momentum_score.csv',
    index=False
)

print(
    "KPI 2 Saved Successfully"
)

retention_df = reentries.copy()

retention_df['next_date'] = (
    retention_df.groupby('song_id')['date']
    .shift(-1)
)

retention_df.head()

retention_df['retention_days'] = (
    retention_df['next_date']
    -
    retention_df['date']
).dt.days

retention_df[
    [
        'song',
        'date',
        'next_date',
        'retention_days'
    ]
].head(20)

retention_summary = (
    retention_df.groupby(
        ['song','artist']
    )['retention_days']
    .mean()
    .reset_index()
)

retention_summary = (
    retention_summary.sort_values(
        by='retention_days',
        ascending=False
    )
)

retention_summary.head(20)

top10_retention = retention_summary.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10_retention,
    x='retention_days',
    y='song'
)

plt.title(
    'Top 10 Songs by Retention Days'
)

plt.show()

retention_summary.to_csv(
    'retention_days.csv',
    index=False
)

print(
    "KPI 3 Saved Successfully"
)

reentries['rank_recovery_speed'] = (
    51 - reentries['position']
)

reentries[
    [
        'song',
        'artist',
        'position',
        'rank_recovery_speed'
    ]
].head()

rank_recovery = (
    reentries.groupby(
        ['song','artist']
    )['rank_recovery_speed']
    .mean()
    .reset_index()
)

rank_recovery = (
    rank_recovery.sort_values(
        by='rank_recovery_speed',
        ascending=False
    )
)

rank_recovery.head(20)

top10_rank = rank_recovery.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10_rank,
    x='rank_recovery_speed',
    y='song'
)

plt.title(
    'Top 10 Songs by Rank Recovery Speed'
)

plt.show()

rank_recovery.to_csv(
    'rank_recovery_speed.csv',
    index=False
)

print(
    "KPI 4 Saved Successfully"
)

album_advantage = (
    reentries.groupby(
        'album_type'
    )
    .agg(
        avg_reentry_position=('position','mean'),
        avg_popularity=('popularity','mean'),
        total_reentries=('song_id','count')
    )
    .reset_index()
)

album_advantage

plt.figure(figsize=(8,5))

sns.barplot(
    data=album_advantage,
    x='album_type',
    y='avg_popularity'
)

plt.title(
    'Album Type vs Average Popularity'
)

plt.show()

album_advantage.to_csv(
    'album_comeback_advantage.csv',
    index=False
)

print(
    "KPI 5 Saved Successfully"
)

fandom_df = reentry_counts.copy()

fandom_df = fandom_df.merge(
    momentum_table,
    on=['song','artist'],
    how='left'
)

fandom_df = fandom_df.merge(
    retention_summary,
    on=['song','artist'],
    how='left'
)

fandom_df.head()

fandom_df['fandom_score'] = (
    fandom_df['reentry_count'] * 0.4
    +
    fandom_df['momentum_score'] * 0.3
    +
    fandom_df['retention_days'].fillna(0) * 0.3
)

fandom_df = fandom_df.sort_values(
    by='fandom_score',
    ascending=False
)

fandom_df.head(20)

top10_fandom = fandom_df.head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    data=top10_fandom,
    x='fandom_score',
    y='song'
)

plt.title(
    'Top 10 Songs by Fandom Intensity Score'
)

plt.show()

fandom_df.to_csv(
    'fandom_intensity_score.csv',
    index=False
)

print(
    "KPI 6 Saved Successfully"
)

import os

for file in os.listdir():
    if file.endswith('.csv'):
        print(file)



import pandas as pd
print(pd.read_csv("dashboard_data/reentry_frequency.csv").columns.tolist())
print(pd.read_csv("dashboard_data/momentum_score.csv").columns.tolist())
print(pd.read_csv("dashboard_data/retention_days.csv").columns.tolist())
print(pd.read_csv("dashboard_data/rank_recovery_speed.csv").columns.tolist())
print(pd.read_csv("dashboard_data/album_comeback_advantage.csv").columns.tolist())
print(pd.read_csv("dashboard_data/fandom_intensity_score.csv").columns.tolist())